# Area512 built-in type declaration.

class I2C
  def write: (Integer i2c_adrs_7, *(Integer | String | Array[Integer]) outputs, ?timeout: Integer, ?nostop: bool) -> Integer

  def read: (Integer i2c_adrs_7, Integer len, *(Integer | String | Array[Integer]) outputs, ?timeout: Integer) -> String

  def scan: (?timeout: Integer) -> nil

  def self.new: (unit: (Symbol | nil), ?frequency: Integer, ?sda_pin: Integer, ?scl_pin: Integer, ?timeout: Integer) -> I2C

end
